version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
  open-pull-requests-limit: 10
  reviewers:
  - rm3l
  labels:
  - dependencies
